export default [
  "Tumhare mentors kaun hain? Career mein guidance kaise mili?",
  "Creator community mein support kaise milta hai?",
  "Friends aur career balance kaise maintain karte ho?",
  "Collaboration projects mein team kaise build karte ho?",
  "Personal life aur professional networking ka balance kya hai?",
  "Sir, OnlyFans jaisa platform banane ke liye kya tech stack chahiye?",
  "Community questions aur interaction kaise handle karte?",
  "How do I start learning full-stack development?",
  "Should I learn theory first or start building?",
  "I'm confused about which framework to choose",
  "How do I deploy my first project?",
  "I keep getting stuck on bugs",
  "NextJS 14 course kaise structure kiya?",
  "Full-stack development seekhna hai, kahan se shuru karu?",
  "Docker ka practical use kya hai projects mein?",
  "Social media pe kahan follow karu aapko?",
  "Industry experience se kya sikha hai aapne?",
  "Full-stack development mein kya focus karna chahiye?",
  "Beginners ke liye roadmap suggest karo",
  "Industry mein projects kaise build karte hain?",
  "Technology trends kya follow karna chahiye?",
  "Sir, open source contribution kaise start karu? Workflow samjha do.",
  "Issues aur pull requests kaise link karte?",
  "Maine ek issue solve kiya lekin mujhe bounty kaise mili?",
  "Issues read karne mein problem aa rahi hai, samjh nahi ata.",
  "Fork vs original repository mein confusion hai.",
  "Skeleton loading fix kaise tha?",
  "Live session mein doubt clear karne ka time milta hai?",
  "DSA sikhna hai ya development pe focus?",
  "DSA seekh liya, ab interview clear karunga?",
  "Social media mein graph kaise use karte?",
  "LeetCode problems solve kiye, ab expert hun?",
  "Course complete karne ke baad guarantee hai job?",
  "35 hours ka course time invest karne layak?"
]
